//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAFPAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALLOWANCE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ALLOWANCE()
        {
            this.JUNIORCEALLOWANCE = new HashSet<JUNIORCEALLOWANCE>();
            this.JUNIORCEPAYROLLALLOWANCE = new HashSet<JUNIORCEPAYROLLALLOWANCE>();
            this.JUNIORCETRIALPAYALLOWANCE = new HashSet<JUNIORCETRIALPAYALLOWANCE>();
            this.OFFICERALLOWANCE = new HashSet<OFFICERALLOWANCE>();
            this.OFFICERPAYROLLALLOWANCE = new HashSet<OFFICERPAYROLLALLOWANCE>();
            this.OFFICERTRIALPAYALLOWANCE = new HashSet<OFFICERTRIALPAYALLOWANCE>();
            this.SENIORCEALLOWANCE = new HashSet<SENIORCEALLOWANCE>();
            this.SENIORCEPAYROLLALLOWANCE = new HashSet<SENIORCEPAYROLLALLOWANCE>();
            this.SENIORCETRIALPAYALLOWANCE = new HashSet<SENIORCETRIALPAYALLOWANCE>();
            this.SOLDIERALLOWANCE = new HashSet<SOLDIERALLOWANCE>();
            this.SOLDIERPAYROLLALLOWANCE = new HashSet<SOLDIERPAYROLLALLOWANCE>();
            this.SOLDIERTRIALPAYALLOWANCE = new HashSet<SOLDIERTRIALPAYALLOWANCE>();
        }
    
        public int ALLOWANCEID { get; set; }
        public string ALLOWANCENAME { get; set; }
        public int STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JUNIORCEALLOWANCE> JUNIORCEALLOWANCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JUNIORCEPAYROLLALLOWANCE> JUNIORCEPAYROLLALLOWANCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JUNIORCETRIALPAYALLOWANCE> JUNIORCETRIALPAYALLOWANCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OFFICERALLOWANCE> OFFICERALLOWANCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OFFICERPAYROLLALLOWANCE> OFFICERPAYROLLALLOWANCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OFFICERTRIALPAYALLOWANCE> OFFICERTRIALPAYALLOWANCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SENIORCEALLOWANCE> SENIORCEALLOWANCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SENIORCEPAYROLLALLOWANCE> SENIORCEPAYROLLALLOWANCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SENIORCETRIALPAYALLOWANCE> SENIORCETRIALPAYALLOWANCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLDIERALLOWANCE> SOLDIERALLOWANCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLDIERPAYROLLALLOWANCE> SOLDIERPAYROLLALLOWANCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLDIERTRIALPAYALLOWANCE> SOLDIERTRIALPAYALLOWANCE { get; set; }
    }
}
