//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAFPAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELETEDOFFICER
    {
        public int DELETEDOFFICERID { get; set; }
        public System.DateTime DATETIMEDELETED { get; set; }
        public string DELETEDBY { get; set; }
        public int OFFICERID { get; set; }
        public int STATUS { get; set; }
    
        public virtual OFFICER OFFICER { get; set; }
    }
}
