//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAFPAY.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBGAFPAYEntities : DbContext
    {
        public DBGAFPAYEntities()
            : base("name=DBGAFPAYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANK> BANK { get; set; }
        public virtual DbSet<BANKNAME> BANKNAME { get; set; }
        public virtual DbSet<BLOODGROUP> BLOODGROUP { get; set; }
        public virtual DbSet<CIVILIANLEVSTEP> CIVILIANLEVSTEP { get; set; }
        public virtual DbSet<COMMISSIONTYPE> COMMISSIONTYPE { get; set; }
        public virtual DbSet<DEDUCTION> DEDUCTION { get; set; }
        public virtual DbSet<DEDUCTIONCLASS> DEDUCTIONCLASS { get; set; }
        public virtual DbSet<GENDER> GENDER { get; set; }
        public virtual DbSet<GENERALSTATUS> GENERALSTATUS { get; set; }
        public virtual DbSet<JUNIORCE> JUNIORCE { get; set; }
        public virtual DbSet<JUNIORCEALLOWANCE> JUNIORCEALLOWANCE { get; set; }
        public virtual DbSet<JUNIORCEBANK> JUNIORCEBANK { get; set; }
        public virtual DbSet<JUNIORCEDEDUCTION> JUNIORCEDEDUCTION { get; set; }
        public virtual DbSet<JUNIORCEIMAGE> JUNIORCEIMAGE { get; set; }
        public virtual DbSet<JUNIORCEMEDP> JUNIORCEMEDP { get; set; }
        public virtual DbSet<JUNIORCEPAYROLL> JUNIORCEPAYROLL { get; set; }
        public virtual DbSet<JUNIORCEPAYROLLALLOWANCE> JUNIORCEPAYROLLALLOWANCE { get; set; }
        public virtual DbSet<JUNIORCEPAYROLLDEDUCTION> JUNIORCEPAYROLLDEDUCTION { get; set; }
        public virtual DbSet<JUNIORCEPROVIDENT> JUNIORCEPROVIDENT { get; set; }
        public virtual DbSet<JUNIORCETRIALPAY> JUNIORCETRIALPAY { get; set; }
        public virtual DbSet<JUNIORCETRIALPAYALLOWANCE> JUNIORCETRIALPAYALLOWANCE { get; set; }
        public virtual DbSet<JUNIORCETRIALPAYDEDUCTION> JUNIORCETRIALPAYDEDUCTION { get; set; }
        public virtual DbSet<MILITARYLEVSTEP> MILITARYLEVSTEP { get; set; }
        public virtual DbSet<OFFICER> OFFICER { get; set; }
        public virtual DbSet<OFFICERALLOWANCE> OFFICERALLOWANCE { get; set; }
        public virtual DbSet<OFFICERBANK> OFFICERBANK { get; set; }
        public virtual DbSet<OFFICERCADETBANK> OFFICERCADETBANK { get; set; }
        public virtual DbSet<OFFICERCADETIMAGE> OFFICERCADETIMAGE { get; set; }
        public virtual DbSet<OFFICERCADETPAYROLL> OFFICERCADETPAYROLL { get; set; }
        public virtual DbSet<OFFICERCADETTRIALPAY> OFFICERCADETTRIALPAY { get; set; }
        public virtual DbSet<OFFICERDEDUCTION> OFFICERDEDUCTION { get; set; }
        public virtual DbSet<OFFICERIMAGE> OFFICERIMAGE { get; set; }
        public virtual DbSet<OFFICERMEDP> OFFICERMEDP { get; set; }
        public virtual DbSet<OFFICERPAYROLL> OFFICERPAYROLL { get; set; }
        public virtual DbSet<OFFICERPAYROLLALLOWANCE> OFFICERPAYROLLALLOWANCE { get; set; }
        public virtual DbSet<OFFICERPAYROLLDEDUCTION> OFFICERPAYROLLDEDUCTION { get; set; }
        public virtual DbSet<OFFICERTRIALPAY> OFFICERTRIALPAY { get; set; }
        public virtual DbSet<OFFICERTRIALPAYALLOWANCE> OFFICERTRIALPAYALLOWANCE { get; set; }
        public virtual DbSet<OFFICERTRIALPAYDEDUCTION> OFFICERTRIALPAYDEDUCTION { get; set; }
        public virtual DbSet<PROVIDENTFUND> PROVIDENTFUND { get; set; }
        public virtual DbSet<RANK> RANK { get; set; }
        public virtual DbSet<RECRUIT> RECRUIT { get; set; }
        public virtual DbSet<RECRUITBANK> RECRUITBANK { get; set; }
        public virtual DbSet<RECRUITCOURSE> RECRUITCOURSE { get; set; }
        public virtual DbSet<RECRUITIMAGE> RECRUITIMAGE { get; set; }
        public virtual DbSet<RECRUITPAYROLL> RECRUITPAYROLL { get; set; }
        public virtual DbSet<RECRUITTRIALPAY> RECRUITTRIALPAY { get; set; }
        public virtual DbSet<REGION> REGION { get; set; }
        public virtual DbSet<RELIGION> RELIGION { get; set; }
        public virtual DbSet<SENIORCEALLOWANCE> SENIORCEALLOWANCE { get; set; }
        public virtual DbSet<SENIORCEBANK> SENIORCEBANK { get; set; }
        public virtual DbSet<SENIORCEDEDUCTION> SENIORCEDEDUCTION { get; set; }
        public virtual DbSet<SENIORCEIMAGE> SENIORCEIMAGE { get; set; }
        public virtual DbSet<SENIORCEMEDP> SENIORCEMEDP { get; set; }
        public virtual DbSet<SENIORCEPAYROLL> SENIORCEPAYROLL { get; set; }
        public virtual DbSet<SENIORCEPAYROLLALLOWANCE> SENIORCEPAYROLLALLOWANCE { get; set; }
        public virtual DbSet<SENIORCEPAYROLLDEDUCTION> SENIORCEPAYROLLDEDUCTION { get; set; }
        public virtual DbSet<SENIORCETRIALPAY> SENIORCETRIALPAY { get; set; }
        public virtual DbSet<SENIORCETRIALPAYALLOWANCE> SENIORCETRIALPAYALLOWANCE { get; set; }
        public virtual DbSet<SENIORCETRIALPAYDEDUCTION> SENIORCETRIALPAYDEDUCTION { get; set; }
        public virtual DbSet<SERVICE> SERVICE { get; set; }
        public virtual DbSet<SOLDIER> SOLDIER { get; set; }
        public virtual DbSet<SOLDIERALLOWANCE> SOLDIERALLOWANCE { get; set; }
        public virtual DbSet<SOLDIERBANK> SOLDIERBANK { get; set; }
        public virtual DbSet<SOLDIERDEDUCTION> SOLDIERDEDUCTION { get; set; }
        public virtual DbSet<SOLDIERIMAGE> SOLDIERIMAGE { get; set; }
        public virtual DbSet<SOLDIERMEDP> SOLDIERMEDP { get; set; }
        public virtual DbSet<SOLDIERPAYROLL> SOLDIERPAYROLL { get; set; }
        public virtual DbSet<SOLDIERPAYROLLALLOWANCE> SOLDIERPAYROLLALLOWANCE { get; set; }
        public virtual DbSet<SOLDIERPAYROLLDEDUCTION> SOLDIERPAYROLLDEDUCTION { get; set; }
        public virtual DbSet<SOLDIERTRIALPAY> SOLDIERTRIALPAY { get; set; }
        public virtual DbSet<SOLDIERTRIALPAYALLOWANCE> SOLDIERTRIALPAYALLOWANCE { get; set; }
        public virtual DbSet<SOLDIERTRIALPAYDEDUCTION> SOLDIERTRIALPAYDEDUCTION { get; set; }
        public virtual DbSet<TITLE> TITLE { get; set; }
        public virtual DbSet<TRAININGCENTER> TRAININGCENTER { get; set; }
        public virtual DbSet<UNIT> UNIT { get; set; }
        public virtual DbSet<GRADE> GRADE { get; set; }
        public virtual DbSet<ALLOWANCE> ALLOWANCE { get; set; }
        public virtual DbSet<SENIORCE> SENIORCE { get; set; }
        public virtual DbSet<OFFICERINTAKE> OFFICERINTAKE { get; set; }
        public virtual DbSet<OFFICERCADET> OFFICERCADET { get; set; }
    
        public virtual ObjectResult<procGetRecruitTrialPayList_Result2> procGetRecruitTrialPayList(Nullable<int> yearPrev, Nullable<int> prev, Nullable<int> yearCurr, Nullable<int> curr, Nullable<int> yearNext, Nullable<int> next)
        {
            var yearPrevParameter = yearPrev.HasValue ?
                new ObjectParameter("yearPrev", yearPrev) :
                new ObjectParameter("yearPrev", typeof(int));
    
            var prevParameter = prev.HasValue ?
                new ObjectParameter("prev", prev) :
                new ObjectParameter("prev", typeof(int));
    
            var yearCurrParameter = yearCurr.HasValue ?
                new ObjectParameter("yearCurr", yearCurr) :
                new ObjectParameter("yearCurr", typeof(int));
    
            var currParameter = curr.HasValue ?
                new ObjectParameter("Curr", curr) :
                new ObjectParameter("Curr", typeof(int));
    
            var yearNextParameter = yearNext.HasValue ?
                new ObjectParameter("yearNext", yearNext) :
                new ObjectParameter("yearNext", typeof(int));
    
            var nextParameter = next.HasValue ?
                new ObjectParameter("next", next) :
                new ObjectParameter("next", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<procGetRecruitTrialPayList_Result2>("procGetRecruitTrialPayList", yearPrevParameter, prevParameter, yearCurrParameter, currParameter, yearNextParameter, nextParameter);
        }
    
        public virtual ObjectResult<progGetOfficerCadetTrialPayList_Result2> progGetOfficerCadetTrialPayList(Nullable<int> yearPrev, Nullable<int> prev, Nullable<int> yearCurr, Nullable<int> curr, Nullable<int> yearNext, Nullable<int> next)
        {
            var yearPrevParameter = yearPrev.HasValue ?
                new ObjectParameter("yearPrev", yearPrev) :
                new ObjectParameter("yearPrev", typeof(int));
    
            var prevParameter = prev.HasValue ?
                new ObjectParameter("prev", prev) :
                new ObjectParameter("prev", typeof(int));
    
            var yearCurrParameter = yearCurr.HasValue ?
                new ObjectParameter("yearCurr", yearCurr) :
                new ObjectParameter("yearCurr", typeof(int));
    
            var currParameter = curr.HasValue ?
                new ObjectParameter("Curr", curr) :
                new ObjectParameter("Curr", typeof(int));
    
            var yearNextParameter = yearNext.HasValue ?
                new ObjectParameter("yearNext", yearNext) :
                new ObjectParameter("yearNext", typeof(int));
    
            var nextParameter = next.HasValue ?
                new ObjectParameter("next", next) :
                new ObjectParameter("next", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<progGetOfficerCadetTrialPayList_Result2>("progGetOfficerCadetTrialPayList", yearPrevParameter, prevParameter, yearCurrParameter, currParameter, yearNextParameter, nextParameter);
        }
    }
}
