//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAFPAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JUNIORCETRIALPAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JUNIORCETRIALPAY()
        {
            this.JUNIORCETRIALPAYALLOWANCE = new HashSet<JUNIORCETRIALPAYALLOWANCE>();
            this.JUNIORCETRIALPAYDEDUCTION = new HashSet<JUNIORCETRIALPAYDEDUCTION>();
        }
    
        public int JUNIORCETRIALPAYID { get; set; }
        public System.DateTime PAYDATE { get; set; }
        public decimal CONSTPAY { get; set; }
        public System.DateTime DATETIMEINSERTED { get; set; }
        public string INSERTEDBY { get; set; }
        public int STATUS { get; set; }
        public int JUNIORCEID { get; set; }
        public int BANKID { get; set; }
        public Nullable<decimal> NETPAY { get; set; }
    
        public virtual BANK BANK { get; set; }
        public virtual JUNIORCE JUNIORCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JUNIORCETRIALPAYALLOWANCE> JUNIORCETRIALPAYALLOWANCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JUNIORCETRIALPAYDEDUCTION> JUNIORCETRIALPAYDEDUCTION { get; set; }
    }
}
