//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAFPAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFFICERTRIALPAYALLOWANCE
    {
        public int OTRIALPAYALLOWANCEID { get; set; }
        public decimal AMOUNT { get; set; }
        public int OTRIALPAYID { get; set; }
        public int ALLOWANCEID { get; set; }
    
        public virtual OFFICERTRIALPAY OFFICERTRIALPAY { get; set; }
        public virtual ALLOWANCE ALLOWANCE { get; set; }
    }
}
