//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAFPAY.Models
{
    using System;
    
    public partial class progGetOfficerCadetTrialPayList_Result2
    {
        public int OCTRIALPAYID { get; set; }
        public decimal CONSTPAY { get; set; }
        public System.DateTime PAYDATE { get; set; }
        public string SERVICENUMBER { get; set; }
        public string SURNAME { get; set; }
        public string OTHERNAME { get; set; }
        public string RANKNAME { get; set; }
    }
}
