//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAFPAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECRUIT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RECRUIT()
        {
            this.DELETEDRECRUIT = new HashSet<DELETEDRECRUIT>();
            this.RECRUITPAYROLL = new HashSet<RECRUITPAYROLL>();
            this.RECRUITTRIALPAY = new HashSet<RECRUITTRIALPAY>();
        }
    
        public int RECRIUTID { get; set; }
        public string SURNAME { get; set; }
        public string OTHERNAME { get; set; }
        public System.DateTime DOB { get; set; }
        public string PHONENUMBER { get; set; }
        public string EMAILADDRESS { get; set; }
        public string GHANAPOSTGPS { get; set; }
        public string RESADDRESS { get; set; }
        public string SERVICENUMBER { get; set; }
        public System.DateTime RECRUITSTARTDATE { get; set; }
        public Nullable<System.DateTime> RECRUITENDDATE { get; set; }
        public string HOMETOWN { get; set; }
        public System.DateTime DATETIMEINSERTED { get; set; }
        public string INSERTEDBY { get; set; }
        public Nullable<System.DateTime> DATETIMEUPDATED { get; set; }
        public string UPDATEDBY { get; set; }
        public int GENDERID { get; set; }
        public int TCID { get; set; }
        public int REGIONID { get; set; }
        public int RANKID { get; set; }
        public int RCID { get; set; }
        public int RELIGIONID { get; set; }
        public int BLOODGROUPID { get; set; }
        public int SERVICEID { get; set; }
        public int GENERALSTATUSID { get; set; }
        public int MILITARYLEVSTEPID { get; set; }
    
        public virtual BLOODGROUP BLOODGROUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELETEDRECRUIT> DELETEDRECRUIT { get; set; }
        public virtual GENDER GENDER { get; set; }
        public virtual GENERALSTATUS GENERALSTATUS { get; set; }
        public virtual MILITARYLEVSTEP MILITARYLEVSTEP { get; set; }
        public virtual RANK RANK { get; set; }
        public virtual RECRUITBANK RECRUITBANK { get; set; }
        public virtual RECRUITIMAGE RECRUITIMAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECRUITPAYROLL> RECRUITPAYROLL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECRUITTRIALPAY> RECRUITTRIALPAY { get; set; }
        public virtual RECRUITCOURSE RECRUITCOURSE { get; set; }
        public virtual REGION REGION { get; set; }
        public virtual RELIGION RELIGION { get; set; }
        public virtual SERVICE SERVICE { get; set; }
        public virtual TRAININGCENTER TRAININGCENTER { get; set; }
    }
}
